# Generated by Django 5.0 on 2024-09-22 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account_classification', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=100)),
                ('account_code', models.CharField(max_length=10, unique=True)),
                ('description', models.CharField(max_length=100)),
                ('financial_statement', models.CharField(max_length=100)),
                ('account_classification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account_classification.accountclassification')),
            ],
        ),
    ]
